import 'babel-polyfill'
// import './class/le-num.js'
// import './class/le-arr.js'
// import './class/le-func.js'
// import './class/le-objExtend.js'
// import './class/le-symbol.js'
// import './class/le-setAndMap.js'
// import './class/le-proxy--Reflect.js'
// import './class/le-class.js'
// import './class/le-promise.js'
// import './class/le-iterator.js'
import './class/le-generator.js'